# Generated by Django 3.1.6 on 2021-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='university',
            field=models.TextField(default='daiict', max_length=150),
        ),
    ]
